namespace: p-g20

resources:
  - ../../base

images:
  - name: ghcr.io/sajiv8/p-g20
    newTag: deploy-1

commonAnnotations:
  p-g20.io/build-sha: d3ade66d14a947111de0907091b6fd707afdc518
  p-g20.io/release-slot: 1