apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p-g20
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sajiv8/P_G20
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: p-g20
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true