# ============================================================================
# Kustomization — Production Overlay
# ============================================================================
# ArgoCD watches this overlay. The CI pipeline updates `newTag` on each push.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rso

resources:
  - ../../base

images:
  - name: ghcr.io/sajiv8/rso-frontend
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b
  - name: ghcr.io/sajiv8/rso-tenant-service
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b
  - name: ghcr.io/sajiv8/rso-user-service
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b
  - name: ghcr.io/sajiv8/rso-resource-service
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b
  - name: ghcr.io/sajiv8/rso-booking-service
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b
  - name: ghcr.io/sajiv8/rso-notification-service
    newTag: 4d83c3b0e2982798dd411a0b12a7458967f8c24b


