# ============================================================================
# Kustomization — Production Overlay
# ============================================================================
# ArgoCD watches this overlay. The CI pipeline updates `newTag` on each push.
# ============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rso

resources:
  - ../../base

images:
  - name: ghcr.io/sajiv8/rso-frontend
<<<<<<< Updated upstream
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-tenant-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-user-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-resource-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-booking-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-notification-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724

=======
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-tenant-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-user-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-resource-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-booking-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
  - name: ghcr.io/sajiv8/rso-notification-service
    newTag: 1b61a8366ff4cc13ea438e97c8ec4494ff1f2724
    
>>>>>>> Stashed changes
