apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p-g20
  namespace: p-g20
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.example.com
      secretName: p-g20-origin-tls
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: p-g20
                port:
                  number: 80